[versions]
activityCompose = "1.12.2"
androidGradlePlugin = "8.13.2"
baselineProfile = "1.4.1"
benchmarkMacroJunit4 = "1.4.1"
browser = "1.9.0"
coil = "3.3.0"
constraintlayoutCompose = "1.1.1"
coreKtx = "1.17.0"
detekt = "1.23.8"
espressoCore = "3.6.1"
firebaseCrashlytics = "3.0.6"
googleServices = "4.4.4"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.3.0"
kotlinx-datetime = "0.7.1"
ksp = "2.3.4"
lifecycleViewmodelCompose = "2.10.0"
loggingInterceptor = "5.3.2"
navigationCompose = "2.9.6"
orbitViewmodel = "11.0.0"
pluto = "2.2.2"
profileinstaller = "1.4.1"
retrofit = "3.0.0"
roomRuntime = "2.8.4"
rules = "1.7.0"
runtimeTracing = "1.9.3"
startupRuntime = "1.2.0"
uiautomator = "2.3.0"
workRuntimeKtx = "2.11.0"
datastore = "1.2.0"
protobufJavalite = "4.33.2"
protobuf = "0.9.6"
metro = "0.9.2"
kotlinxSerialization = "1.9.0"
kotlinxSerializationConvertor = "3.0.0"
ktorClientAndroid = "3.3.3"


[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runtime-tracing = { module = "androidx.compose.runtime:runtime-tracing", version.ref = "runtimeTracing" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
bundle-core = { module = "com.plutolib.plugins:bundle-core", version.ref = "pluto" }
bundle-core-no-op = { module = "com.plutolib.plugins:bundle-core-no-op", version.ref = "pluto" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-ktor = { module  = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
compose-bom = "androidx.compose:compose-bom:2025.12.01"
compose-ui = { module = "androidx.compose.ui:ui" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
firebase-bom = "com.google.firebase:firebase-bom:34.7.0"
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
junit = { module = "junit:junit", version.ref = "junit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbitViewmodel" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbitViewmodel" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
pluto = { module = "com.plutolib:pluto", version.ref = "pluto" }
pluto-no-op = { module = "com.plutolib:pluto-no-op", version.ref = "pluto" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobufJavalite" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization"}
kotlinx-serialization-convertor =  { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "kotlinxSerializationConvertor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineProfile" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics"}
google-services = { id = 'com.google.gms.google-services', version.ref = "googleServices"}
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
